-- Modify the NotificationType enum to add ORDER_STATUS_CHANGED
ALTER TABLE `Notifications` MODIFY `type` ENUM('WISHLIST_PRICE_DROP', 'WISHLIST_NEW_COUPON', 'ORDER_STATUS_CHANGED', 'SYSTEM') NOT NULL;
